/** Produtos da Lojinha — vocabulário concreto de 6-10 anos, tudo PT-BR. */
export const PRODUTOS: Array<{ emoji: string; nome: string }> = [
  { emoji: "🍎", nome: "maçã" },
  { emoji: "🍌", nome: "banana" },
  { emoji: "🍓", nome: "morango" },
  { emoji: "🍉", nome: "melancia" },
  { emoji: "🥕", nome: "cenoura" },
  { emoji: "🍞", nome: "pão" },
  { emoji: "🧀", nome: "queijo" },
  { emoji: "🥛", nome: "leite" },
  { emoji: "🍦", nome: "sorvete" },
  { emoji: "🍭", nome: "pirulito" },
  { emoji: "🍿", nome: "pipoca" },
  { emoji: "🧃", nome: "suquinho" },
  { emoji: "⚽", nome: "bola" },
  { emoji: "🪁", nome: "pipa" },
  { emoji: "🧸", nome: "ursinho" },
  { emoji: "🎈", nome: "balão" },
  { emoji: "📚", nome: "livro" },
  { emoji: "✏️", nome: "lápis" },
  { emoji: "🖍️", nome: "giz de cera" },
  { emoji: "🎨", nome: "tinta" },
  { emoji: "🧩", nome: "quebra-cabeça" },
  { emoji: "🚗", nome: "carrinho" },
  { emoji: "🪆", nome: "boneca" },
  { emoji: "🎲", nome: "dado" },
];
