// GERADO por scripts/processar-banco-colorir.py — não editar à mão.
// Origem: banco pessoal de páginas para colorir (uso familiar).
import type { PaginaImagem } from "./tipos";

export const PAGINAS_IMAGEM: PaginaImagem[] = [
  { slug: "cartoon-horse-standing-in-a-corral-horse-coloring-pages", nome: "cartoon cavalo standing em corral cavalo", categoria: "animais", src: "/colorir-img/animais/cartoon-horse-standing-in-a-corral-horse-coloring-pages.webp", largura: 1100, altura: 850 },
  { slug: "cat-peeking-out-of-a-box-cat-coloring-pages", nome: "gato peeking out de box gato", categoria: "animais", src: "/colorir-img/animais/cat-peeking-out-of-a-box-cat-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cat-playing-with-cute-bugs-cat-coloring-pages", nome: "gato brincando com fofo bugs gato", categoria: "animais", src: "/colorir-img/animais/cat-playing-with-cute-bugs-cat-coloring-pages.webp", largura: 1100, altura: 850 },
  { slug: "cute-cat-making-muffins-cat-coloring-pages", nome: "fofo gato making muffins gato", categoria: "animais", src: "/colorir-img/animais/cute-cat-making-muffins-cat-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-cat-sitting-in-the-yard-cat-coloring-pages", nome: "fofo gato sitting em yard gato", categoria: "animais", src: "/colorir-img/animais/cute-cat-sitting-in-the-yard-cat-coloring-pages.webp", largura: 1100, altura: 850 },
  { slug: "cute-dog-playing-with-a-ball", nome: "fofo cachorro brincando com bola", categoria: "animais", src: "/colorir-img/animais/cute-dog-playing-with-a-ball.webp", largura: 850, altura: 1100 },
  { slug: "cute-dog-running-through-the-woods", nome: "fofo cachorro running through woods", categoria: "animais", src: "/colorir-img/animais/cute-dog-running-through-the-woods.webp", largura: 850, altura: 1100 },
  { slug: "cute-dog-standing-by-a-palm-tree", nome: "fofo cachorro standing by palm tree", categoria: "animais", src: "/colorir-img/animais/cute-dog-standing-by-a-palm-tree.webp", largura: 1100, altura: 850 },
  { slug: "cute-fluffy-dog-coloring-page", nome: "fofo fluffy cachorro", categoria: "animais", src: "/colorir-img/animais/cute-fluffy-dog-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "cute-horse-standing-in-front-of-a-barn-horse-coloring-pages", nome: "fofo cavalo standing em front de barn cavalo", categoria: "animais", src: "/colorir-img/animais/cute-horse-standing-in-front-of-a-barn-horse-coloring-pages.webp", largura: 1100, altura: 850 },
  { slug: "cute-horse-with-spots-horse-coloring-pages", nome: "fofo cavalo com spots cavalo", categoria: "animais", src: "/colorir-img/animais/cute-horse-with-spots-horse-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-puppy-eating-a-bone-puppy-coloring-page", nome: "fofo cachorrinho eating bone cachorrinho", categoria: "animais", src: "/colorir-img/animais/cute-puppy-eating-a-bone-puppy-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "cute-puppy-playing-with-balloons-puppy-coloring-pages", nome: "fofo cachorrinho brincando com balloons cachorrinho", categoria: "animais", src: "/colorir-img/animais/cute-puppy-playing-with-balloons-puppy-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-puppy-sitting-in-a-puddle-of-water-puppy-coloring-pages", nome: "fofo cachorrinho sitting em puddle de water cachorrinho", categoria: "animais", src: "/colorir-img/animais/cute-puppy-sitting-in-a-puddle-of-water-puppy-coloring-pages.webp", largura: 1100, altura: 850 },
  { slug: "cute-smiling-horse-coloring-pages", nome: "fofo smiling cavalo", categoria: "animais", src: "/colorir-img/animais/cute-smiling-horse-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-spotted-puppy-coloring-page", nome: "fofo spotted cachorrinho", categoria: "animais", src: "/colorir-img/animais/cute-spotted-puppy-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "cute-walking-cat-coloring-page", nome: "fofo walking gato", categoria: "animais", src: "/colorir-img/animais/cute-walking-cat-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "easy-to-color-dog-with-long-ears", nome: "easy to color cachorro com long ears", categoria: "animais", src: "/colorir-img/animais/easy-to-color-dog-with-long-ears.webp", largura: 850, altura: 1100 },
  { slug: "easy-to-color-puppy-coloring-page", nome: "easy to color cachorrinho", categoria: "animais", src: "/colorir-img/animais/easy-to-color-puppy-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "fluffy-puppy-coloring-page", nome: "fluffy cachorrinho", categoria: "animais", src: "/colorir-img/animais/fluffy-puppy-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "fun-to-color-silly-dog-with-big-eyes", nome: "fun to color silly cachorro com big eyes", categoria: "animais", src: "/colorir-img/animais/fun-to-color-silly-dog-with-big-eyes.webp", largura: 1100, altura: 850 },
  { slug: "girl-with-duck", nome: "girl com duck", categoria: "animais", src: "/colorir-img/animais/girl-with-duck.webp", largura: 851, altura: 1100 },
  { slug: "hand-sketched-horse-running-in-the-rain-horse-coloring-page", nome: "hand sketched cavalo running em rain cavalo", categoria: "animais", src: "/colorir-img/animais/hand-sketched-horse-running-in-the-rain-horse-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "horse-wearing-a-saddle-horse-coloring-pages", nome: "cavalo wearing saddle cavalo", categoria: "animais", src: "/colorir-img/animais/horse-wearing-a-saddle-horse-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "lemon-shark", nome: "lemon tubarão", categoria: "animais", src: "/colorir-img/animais/lemon-shark.webp", largura: 1100, altura: 392 },
  { slug: "lion-line-art", nome: "leão line art", categoria: "animais", src: "/colorir-img/animais/lion-line-art.webp", largura: 1100, altura: 760 },
  { slug: "whale", nome: "baleia", categoria: "animais", src: "/colorir-img/animais/whale.webp", largura: 1100, altura: 473 },
  { slug: "white-shark", nome: "white tubarão", categoria: "animais", src: "/colorir-img/animais/white-shark.webp", largura: 1100, altura: 447 },
  { slug: "artist-dragon-painting-a-picture", nome: "artist dragão pintando picture", categoria: "castelo", src: "/colorir-img/castelo/artist-dragon-painting-a-picture.webp", largura: 1100, altura: 850 },
  { slug: "artist-unicorn-painting-on-canvas-coloring-page", nome: "artist unicórnio pintando em canvas", categoria: "castelo", src: "/colorir-img/castelo/artist-unicorn-painting-on-canvas-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "baby-dragon-with-spots", nome: "bebê dragão com spots", categoria: "castelo", src: "/colorir-img/castelo/baby-dragon-with-spots.webp", largura: 1100, altura: 850 },
  { slug: "baby-unicorn-in-gift-box-coloring-page", nome: "bebê unicórnio em gift box", categoria: "castelo", src: "/colorir-img/castelo/baby-unicorn-in-gift-box-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "baker-unicorn-holding-cupcakes-tray-coloring-page", nome: "baker unicórnio holding cupcakes tray", categoria: "castelo", src: "/colorir-img/castelo/baker-unicorn-holding-cupcakes-tray-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "chubby-unicorn-eating-giant-donut-coloring-page", nome: "chubby unicórnio eating giant donut", categoria: "castelo", src: "/colorir-img/castelo/chubby-unicorn-eating-giant-donut-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "cool-unicorn-riding-a-skateboard-coloring-page", nome: "cool unicórnio montando skateboard", categoria: "castelo", src: "/colorir-img/castelo/cool-unicorn-riding-a-skateboard-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "cute-baby-dragon", nome: "fofo bebê dragão", categoria: "castelo", src: "/colorir-img/castelo/cute-baby-dragon.webp", largura: 1100, altura: 850 },
  { slug: "cute-dragon-playing-in-the-mountains", nome: "fofo dragão brincando em mountains", categoria: "castelo", src: "/colorir-img/castelo/cute-dragon-playing-in-the-mountains.webp", largura: 850, altura: 1100 },
  { slug: "cute-dragon-sitting-in-the-clouds", nome: "fofo dragão sitting em nuvens", categoria: "castelo", src: "/colorir-img/castelo/cute-dragon-sitting-in-the-clouds.webp", largura: 1100, altura: 850 },
  { slug: "cute-dragon-walking-by-a-castle", nome: "fofo dragão walking by castelo", categoria: "castelo", src: "/colorir-img/castelo/cute-dragon-walking-by-a-castle.webp", largura: 1100, altura: 850 },
  { slug: "cute-princess-surrounded-with-flowers", nome: "fofo princesa surrounded com flores", categoria: "castelo", src: "/colorir-img/castelo/cute-princess-surrounded-with-flowers.webp", largura: 850, altura: 1100 },
  { slug: "cute-unicorn-in-bubble-bath-coloring-page", nome: "fofo unicórnio em bubble bath", categoria: "castelo", src: "/colorir-img/castelo/cute-unicorn-in-bubble-bath-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "cute-unicorn-sleeping-on-moon-coloring-page", nome: "fofo unicórnio dormindo em lua", categoria: "castelo", src: "/colorir-img/castelo/cute-unicorn-sleeping-on-moon-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "dragon-with-horn", nome: "dragão com horn", categoria: "castelo", src: "/colorir-img/castelo/dragon-with-horn.webp", largura: 1100, altura: 730 },
  { slug: "fairy-riding-on-magical-unicorn-coloring-page", nome: "fada montando em magical unicórnio", categoria: "castelo", src: "/colorir-img/castelo/fairy-riding-on-magical-unicorn-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "geometric-shape-low-poly-unicorn-coloring-page", nome: "geometric shape low poly unicórnio", categoria: "castelo", src: "/colorir-img/castelo/geometric-shape-low-poly-unicorn-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "happy-princess-standing-in-front-of-a-castle", nome: "feliz princesa standing em front de castelo", categoria: "castelo", src: "/colorir-img/castelo/happy-princess-standing-in-front-of-a-castle.webp", largura: 850, altura: 1100 },
  { slug: "happy-unicorn-holding-heart-balloons-coloring-page", nome: "feliz unicórnio holding heart balloons", categoria: "castelo", src: "/colorir-img/castelo/happy-unicorn-holding-heart-balloons-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "intricate-mandala-unicorn-head-pattern-coloring-page", nome: "intricate mandala unicórnio head pattern", categoria: "castelo", src: "/colorir-img/castelo/intricate-mandala-unicorn-head-pattern-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "mother-unicorn-nuzzling-baby-foal-coloring-page", nome: "mother unicórnio nuzzling bebê foal", categoria: "castelo", src: "/colorir-img/castelo/mother-unicorn-nuzzling-baby-foal-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "playful-unicorn-sliding-down-rainbow-coloring-page", nome: "playful unicórnio sliding down arco-íris", categoria: "castelo", src: "/colorir-img/castelo/playful-unicorn-sliding-down-rainbow-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "portrait-of-unicorn-with-flowers-coloring-page", nome: "portrait de unicórnio com flores", categoria: "castelo", src: "/colorir-img/castelo/portrait-of-unicorn-with-flowers-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "pretty-princess-holding-a-flower", nome: "pretty princesa holding flor", categoria: "castelo", src: "/colorir-img/castelo/pretty-princess-holding-a-flower.webp", largura: 850, altura: 1100 },
  { slug: "pretty-princess-holding-a-wand", nome: "pretty princesa holding wand", categoria: "castelo", src: "/colorir-img/castelo/pretty-princess-holding-a-wand.webp", largura: 850, altura: 1100 },
  { slug: "pretty-princess-leading-a-unicorn", nome: "pretty princesa leading unicórnio", categoria: "castelo", src: "/colorir-img/castelo/pretty-princess-leading-a-unicorn.webp", largura: 1100, altura: 850 },
  { slug: "pretty-princess-riding-a-horse", nome: "pretty princesa montando cavalo", categoria: "castelo", src: "/colorir-img/castelo/pretty-princess-riding-a-horse.webp", largura: 850, altura: 1100 },
  { slug: "pretty-princess-smelling-a-flower", nome: "pretty princesa smelling flor", categoria: "castelo", src: "/colorir-img/castelo/pretty-princess-smelling-a-flower.webp", largura: 850, altura: 1100 },
  { slug: "queen-riding-bicycle-frame-line-art-by-richardsdrawings", nome: "queen montando bicycle frame line art by richardsdrawings", categoria: "castelo", src: "/colorir-img/castelo/queen-riding-bicycle-frame-line-art-by-richardsdrawings.webp", largura: 1100, altura: 907 },
  { slug: "queen-riding-bicycle-isolated-by-richardsdrawings", nome: "queen montando bicycle isolated by richardsdrawings", categoria: "castelo", src: "/colorir-img/castelo/queen-riding-bicycle-isolated-by-richardsdrawings.webp", largura: 1041, altura: 1100 },
  { slug: "rockstar-unicorn-playing-electric-guitar-coloring-page", nome: "rockstar unicórnio brincando electric violão", categoria: "castelo", src: "/colorir-img/castelo/rockstar-unicorn-playing-electric-guitar-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "silhouette-unicorn-under-starry-night-coloring-page", nome: "silhouette unicórnio under starry night", categoria: "castelo", src: "/colorir-img/castelo/silhouette-unicorn-under-starry-night-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "smart-unicorn-reading-a-book-coloring-page", nome: "smart unicórnio lendo", categoria: "castelo", src: "/colorir-img/castelo/smart-unicorn-reading-a-book-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "smiling-cartoon-dragon-coloring-page", nome: "smiling cartoon dragão", categoria: "castelo", src: "/colorir-img/castelo/smiling-cartoon-dragon-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "space-unicorn-flying-past-planets-coloring-page", nome: "space unicórnio voando past planets", categoria: "castelo", src: "/colorir-img/castelo/space-unicorn-flying-past-planets-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "tyrannosaurus-rex-dinosaur-walking-down-a-ladder", nome: "tyrannosaurus rex dinossauro walking down ladder", categoria: "castelo", src: "/colorir-img/castelo/tyrannosaurus-rex-dinosaur-walking-down-a-ladder.webp", largura: 850, altura: 1100 },
  { slug: "underwater-mermaid-unicorn-swimming-coloring-page", nome: "underwater sereia unicórnio swimming", categoria: "castelo", src: "/colorir-img/castelo/underwater-mermaid-unicorn-swimming-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-drinking-from-waterfall-stream-coloring-page", nome: "unicórnio drinking from waterfall stream", categoria: "castelo", src: "/colorir-img/castelo/unicorn-drinking-from-waterfall-stream-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-in-enchanted-mushroom-forest-coloring-page", nome: "unicórnio em enchanted cogumelo forest", categoria: "castelo", src: "/colorir-img/castelo/unicorn-in-enchanted-mushroom-forest-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-looking-at-fairy-castle-coloring-page", nome: "unicórnio looking at fada castelo", categoria: "castelo", src: "/colorir-img/castelo/unicorn-looking-at-fairy-castle-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-looking-at-mirror-reflection-coloring-page", nome: "unicórnio looking at mirror reflection", categoria: "castelo", src: "/colorir-img/castelo/unicorn-looking-at-mirror-reflection-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-love-line-art-by-richardsdrawings", nome: "unicórnio love line art by richardsdrawings", categoria: "castelo", src: "/colorir-img/castelo/unicorn-love-line-art-by-richardsdrawings.webp", largura: 1100, altura: 1100 },
  { slug: "unicorn-touching-noses-with-kitten-coloring-page", nome: "unicórnio touching noses com gatinho", categoria: "castelo", src: "/colorir-img/castelo/unicorn-touching-noses-with-kitten-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-with-big-ice-cream-coloring-page", nome: "unicórnio com big ice cream", categoria: "castelo", src: "/colorir-img/castelo/unicorn-with-big-ice-cream-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-with-butterflies-on-nose-coloring-page", nome: "unicórnio com borboletas em nose", categoria: "castelo", src: "/colorir-img/castelo/unicorn-with-butterflies-on-nose-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-with-long-flowing-mane-coloring-page", nome: "unicórnio com long flowing mane", categoria: "castelo", src: "/colorir-img/castelo/unicorn-with-long-flowing-mane-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "unicorn-with-swirling-floral-mane-coloring-page", nome: "unicórnio com swirling floral mane", categoria: "castelo", src: "/colorir-img/castelo/unicorn-with-swirling-floral-mane-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "winged-pegasus-unicorn-flying-high-coloring-page", nome: "winged pegasus unicórnio voando high", categoria: "castelo", src: "/colorir-img/castelo/winged-pegasus-unicorn-flying-high-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "a-boy-playing-soccer", nome: "boy brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/a-boy-playing-soccer.webp", largura: 779, altura: 1100 },
  { slug: "baseball-player", nome: "beisebol jogador", categoria: "esportes", src: "/colorir-img/esportes/baseball-player.webp", largura: 440, altura: 1100 },
  { slug: "basketball-and-goal-basketball-coloring-pages", nome: "basquete e gol basquete", categoria: "esportes", src: "/colorir-img/esportes/basketball-and-goal-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "basketball-and-uniform-basketball-coloring-pages", nome: "basquete e uniform basquete", categoria: "esportes", src: "/colorir-img/esportes/basketball-and-uniform-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "basketball-coloring-page", nome: "basquete", categoria: "esportes", src: "/colorir-img/esportes/basketball-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "basketball-dropping-into-a-hoop-basketball-coloring-pages", nome: "basquete dropping into hoop basquete", categoria: "esportes", src: "/colorir-img/esportes/basketball-dropping-into-a-hoop-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "basketball-player", nome: "basquete jogador", categoria: "esportes", src: "/colorir-img/esportes/basketball-player.webp", largura: 594, altura: 1100 },
  { slug: "basketball-shoes-and-basketball-coloring-pages", nome: "basquete shoes e basquete", categoria: "esportes", src: "/colorir-img/esportes/basketball-shoes-and-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "bear-playing-soccer-coloring-pages", nome: "urso brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/bear-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "bulldog-playing-basketball-coloring-pages", nome: "bulldog brincando basquete", categoria: "esportes", src: "/colorir-img/esportes/bulldog-playing-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cartoon-bear-dribbling-a-basketball-coloring-pages", nome: "cartoon urso dribbling basquete", categoria: "esportes", src: "/colorir-img/esportes/cartoon-bear-dribbling-a-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cartoon-lion-playing-soccer-coloring-pages", nome: "cartoon leão brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/cartoon-lion-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-bear-dunking-a-basketball-coloring-pages", nome: "fofo urso dunking basquete", categoria: "esportes", src: "/colorir-img/esportes/cute-bear-dunking-a-basketball-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-bear-scoring-a-goal-playing-soccer-coloring-pages", nome: "fofo urso scoring gol brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/cute-bear-scoring-a-goal-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-fox-playing-soccer-in-the-street-soccer-coloring-pages", nome: "fofo fox brincando futebol em street futebol", categoria: "esportes", src: "/colorir-img/esportes/cute-fox-playing-soccer-in-the-street-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "cute-giraffe-playing-soccer-in-the-jungle-soccer-coloring-pa", nome: "fofo giraffe brincando futebol em jungle futebol", categoria: "esportes", src: "/colorir-img/esportes/cute-giraffe-playing-soccer-in-the-jungle-soccer-coloring-pa.webp", largura: 850, altura: 1100 },
  { slug: "easy-to-color-fox-playing-soccer-coloring-pages", nome: "easy to color fox brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/easy-to-color-fox-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "easy-to-color-soccer-ball-soccer-coloring-pages", nome: "easy to color futebol bola futebol", categoria: "esportes", src: "/colorir-img/esportes/easy-to-color-soccer-ball-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "four-boys-playing-soccer-coloring-pages", nome: "four boys brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/four-boys-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "funny-bear-playing-soccer-coloring-pages", nome: "funny urso brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/funny-bear-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "lion-playing-soccer-coloring-pages", nome: "leão brincando futebol", categoria: "esportes", src: "/colorir-img/esportes/lion-playing-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "robot-soccer-coloring-pages", nome: "robô futebol", categoria: "esportes", src: "/colorir-img/esportes/robot-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "soccer-ball-in-grass-soccer-coloring-pages", nome: "futebol bola em grass futebol", categoria: "esportes", src: "/colorir-img/esportes/soccer-ball-in-grass-soccer-coloring-pages.webp", largura: 850, altura: 1100 },
  { slug: "soccer-playing-boy", nome: "futebol brincando boy", categoria: "esportes", src: "/colorir-img/esportes/soccer-playing-boy.webp", largura: 829, altura: 1100 },
  { slug: "swimming-fairy", nome: "swimming fada", categoria: "esportes", src: "/colorir-img/esportes/swimming-fairy.webp", largura: 1100, altura: 440 },
  { slug: "tennis-ball", nome: "tênis bola", categoria: "esportes", src: "/colorir-img/esportes/tennis-ball.webp", largura: 1078, altura: 1100 },
  { slug: "tennis-player", nome: "tênis jogador", categoria: "esportes", src: "/colorir-img/esportes/tennis-player.webp", largura: 484, altura: 1100 },
  { slug: "underwater-scene-by-mogumoguo", nome: "underwater scene by mogumoguo", categoria: "esportes", src: "/colorir-img/esportes/underwater-scene-by-mogumoguo.webp", largura: 1100, altura: 660 },
  { slug: "vintage-baseball-player-illustration", nome: "vintage beisebol jogador illustration", categoria: "esportes", src: "/colorir-img/esportes/vintage-baseball-player-illustration.webp", largura: 909, altura: 1100 },
  { slug: "abstract-snowflake", nome: "abstract snowflake", categoria: "natureza", src: "/colorir-img/natureza/abstract-snowflake.webp", largura: 1085, altura: 1100 },
  { slug: "anemone-patens", nome: "anemone patens", categoria: "natureza", src: "/colorir-img/natureza/anemone-patens.webp", largura: 1100, altura: 846 },
  { slug: "aster-conspicuus", nome: "aster conspicuus", categoria: "natureza", src: "/colorir-img/natureza/aster-conspicuus.webp", largura: 814, altura: 1100 },
  { slug: "bumblebee-meeting-a-butterfly-coloring-page", nome: "bumblebee meeting borboleta", categoria: "natureza", src: "/colorir-img/natureza/bumblebee-meeting-a-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "butterfly", nome: "borboleta", categoria: "natureza", src: "/colorir-img/natureza/butterfly.webp", largura: 787, altura: 1100 },
  { slug: "butterfly-line-art", nome: "borboleta line art", categoria: "natureza", src: "/colorir-img/natureza/butterfly-line-art.webp", largura: 1100, altura: 902 },
  { slug: "cherry-blossom-branch-butterfly-coloring-page", nome: "cherry blossom branch borboleta", categoria: "natureza", src: "/colorir-img/natureza/cherry-blossom-branch-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "coloring-book-butterfly", nome: "borboleta", categoria: "natureza", src: "/colorir-img/natureza/coloring-book-butterfly.webp", largura: 1100, altura: 1051 },
  { slug: "cute-caterpillar-and-butterfly-coloring-page", nome: "fofo caterpillar e borboleta", categoria: "natureza", src: "/colorir-img/natureza/cute-caterpillar-and-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "cute-smiling-cartoon-butterfly-coloring-page", nome: "fofo smiling cartoon borboleta", categoria: "natureza", src: "/colorir-img/natureza/cute-smiling-cartoon-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "delicate-lace-texture-butterfly-coloring-page", nome: "delicate lace texture borboleta", categoria: "natureza", src: "/colorir-img/natureza/delicate-lace-texture-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "flower-2", nome: "flor", categoria: "natureza", src: "/colorir-img/natureza/flower-2.webp", largura: 807, altura: 1100 },
  { slug: "flowing-ribbon-wings-butterfly-coloring-page", nome: "flowing ribbon wings borboleta", categoria: "natureza", src: "/colorir-img/natureza/flowing-ribbon-wings-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "fluffy-clouds-and-butterfly-coloring-page", nome: "fluffy nuvens e borboleta", categoria: "natureza", src: "/colorir-img/natureza/fluffy-clouds-and-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "geometric-crystal-wings-butterfly-coloring-page", nome: "geometric crystal wings borboleta", categoria: "natureza", src: "/colorir-img/natureza/geometric-crystal-wings-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "kitten-tree", nome: "gatinho tree", categoria: "natureza", src: "/colorir-img/natureza/kitten-tree.webp", largura: 851, altura: 1100 },
  { slug: "love-heart-pattern-butterfly-coloring-page", nome: "love heart pattern borboleta", categoria: "natureza", src: "/colorir-img/natureza/love-heart-pattern-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "magical-fairy-dust-butterfly-coloring-page", nome: "magical fada dust borboleta", categoria: "natureza", src: "/colorir-img/natureza/magical-fairy-dust-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "mason-jar-with-butterfly-coloring-page", nome: "mason potinho com borboleta", categoria: "natureza", src: "/colorir-img/natureza/mason-jar-with-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "mechanical-steampunk-gear-butterfly-coloring-page", nome: "mechanical steampunk gear borboleta", categoria: "natureza", src: "/colorir-img/natureza/mechanical-steampunk-gear-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "moon-and-stars-butterfly-coloring-page", nome: "lua e stars borboleta", categoria: "natureza", src: "/colorir-img/natureza/moon-and-stars-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "mosaic-tile-pattern-butterfly-coloring-page", nome: "mosaic tile pattern borboleta", categoria: "natureza", src: "/colorir-img/natureza/mosaic-tile-pattern-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "peacock-feather-eyes-butterfly-coloring-page", nome: "peacock feather eyes borboleta", categoria: "natureza", src: "/colorir-img/natureza/peacock-feather-eyes-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "prickly-cactus-flower-butterfly-coloring-page", nome: "prickly cacto flor borboleta", categoria: "natureza", src: "/colorir-img/natureza/prickly-cactus-flower-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "puppy-with-butterfly-on-nose-coloring-page", nome: "cachorrinho com borboleta em nose", categoria: "natureza", src: "/colorir-img/natureza/puppy-with-butterfly-on-nose-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "realistic-monarch-butterfly-on-sunflower-coloring-page", nome: "realistic monarch borboleta em girassol", categoria: "natureza", src: "/colorir-img/natureza/realistic-monarch-butterfly-on-sunflower-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "simple-polka-dot-butterfly-coloring-page", nome: "simple polka dot borboleta", categoria: "natureza", src: "/colorir-img/natureza/simple-polka-dot-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "sleeping-closed-wings-butterfly-coloring-page", nome: "dormindo closed wings borboleta", categoria: "natureza", src: "/colorir-img/natureza/sleeping-closed-wings-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "spotted-mushroom-and-butterfly-coloring-page", nome: "spotted cogumelo e borboleta", categoria: "natureza", src: "/colorir-img/natureza/spotted-mushroom-and-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "stained-glass-style-butterfly-coloring-page", nome: "stained glass style borboleta", categoria: "natureza", src: "/colorir-img/natureza/stained-glass-style-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "three-flying-butterfly-trio-coloring-page", nome: "three voando borboleta trio", categoria: "natureza", src: "/colorir-img/natureza/three-flying-butterfly-trio-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "tropical-blue-morpho-butterfly-coloring-page", nome: "tropical blue morpho borboleta", categoria: "natureza", src: "/colorir-img/natureza/tropical-blue-morpho-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "whimsical-curly-antenna-butterfly-coloring-page", nome: "whimsical curly antenna borboleta", categoria: "natureza", src: "/colorir-img/natureza/whimsical-curly-antenna-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "zebra-striped-wings-butterfly-coloring-page", nome: "zebra striped wings borboleta", categoria: "natureza", src: "/colorir-img/natureza/zebra-striped-wings-butterfly-coloring-page.webp", largura: 770, altura: 1100 },
  { slug: "airplane-with-propeller-outline", nome: "avião com propeller outline", categoria: "veiculos", src: "/colorir-img/veiculos/airplane-with-propeller-outline.webp", largura: 1100, altura: 783 },
  { slug: "auto-car", nome: "auto carro", categoria: "veiculos", src: "/colorir-img/veiculos/auto-car.webp", largura: 1100, altura: 575 },
  { slug: "cartoon-style-taxi-cab-coloring-page", nome: "cartoon style táxi cab", categoria: "veiculos", src: "/colorir-img/veiculos/cartoon-style-taxi-cab-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "cute-car-with-a-mouse-driving-coloring-page", nome: "fofo carro com mouse driving", categoria: "veiculos", src: "/colorir-img/veiculos/cute-car-with-a-mouse-driving-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "cute-race-car-sitting-in-front-of-mountains-coloring-page", nome: "fofo corrida carro sitting em front de mountains", categoria: "veiculos", src: "/colorir-img/veiculos/cute-race-car-sitting-in-front-of-mountains-coloring-page.webp", largura: 850, altura: 1100 },
  { slug: "deux-camions-de-levage", nome: "deux camions de levage", categoria: "veiculos", src: "/colorir-img/veiculos/deux-camions-de-levage.webp", largura: 1100, altura: 532 },
  { slug: "deux-camions-noirs", nome: "deux camions noirs", categoria: "veiculos", src: "/colorir-img/veiculos/deux-camions-noirs.webp", largura: 1100, altura: 602 },
  { slug: "emergency-vehicles-black-and-white", nome: "emergency vehicles black e white", categoria: "veiculos", src: "/colorir-img/veiculos/emergency-vehicles-black-and-white.webp", largura: 907, altura: 1100 },
  { slug: "jet-liner", nome: "avião a jato liner", categoria: "veiculos", src: "/colorir-img/veiculos/jet-liner.webp", largura: 1100, altura: 1100 },
  { slug: "p38-fighter-plane-ww2", nome: "p38 fighter avião ww2", categoria: "veiculos", src: "/colorir-img/veiculos/p38-fighter-plane-ww2.webp", largura: 1100, altura: 1100 },
  { slug: "pickup-et-camion-noirs", nome: "pickup et camion noirs", categoria: "veiculos", src: "/colorir-img/veiculos/pickup-et-camion-noirs.webp", largura: 1100, altura: 637 },
  { slug: "realistic-car-coloring-page", nome: "realistic carro", categoria: "veiculos", src: "/colorir-img/veiculos/realistic-car-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "realistic-sports-car-coloring-page", nome: "realistic sports carro", categoria: "veiculos", src: "/colorir-img/veiculos/realistic-sports-car-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "silly-car-with-eyes-sitting-by-an-apple-tree-coloring-page", nome: "silly carro com eyes sitting by apple tree", categoria: "veiculos", src: "/colorir-img/veiculos/silly-car-with-eyes-sitting-by-an-apple-tree-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "sports-car-coloring-page", nome: "sports carro", categoria: "veiculos", src: "/colorir-img/veiculos/sports-car-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "three-fun-cars-coloring-page", nome: "three fun carros", categoria: "veiculos", src: "/colorir-img/veiculos/three-fun-cars-coloring-page.webp", largura: 1100, altura: 850 },
  { slug: "vw-beetle-classic", nome: "vw fusca classic", categoria: "veiculos", src: "/colorir-img/veiculos/vw-beetle-classic.webp", largura: 1100, altura: 801 },
  { slug: "zaz-965", nome: "desenho de veiculos 18", categoria: "veiculos", src: "/colorir-img/veiculos/zaz-965.webp", largura: 1100, altura: 650 },
];

export function buscarImagem(slug: string | undefined): PaginaImagem | undefined {
  if (!slug) return undefined;
  return PAGINAS_IMAGEM.find((p) => p.slug === slug);
}

export function imagensDaCategoria(categoria: string): PaginaImagem[] {
  return PAGINAS_IMAGEM.filter((p) => p.categoria === categoria);
}
